### ISSUE TITLE
Adding @apiHeader with group fails compilation

### ISSUE THREAD

**Issue by perry-mitchell** [rigwild/apidoc-markdown#12]
## Describe the bug
When compiling the documentation (using apidoc **first**), adding the following causes a fatal error to be thrown:

```javascript
/**
 * <snip>
 * @apiHeader (Response Headers) {String} Location Valid location
 * <snip>
 */
```

The error:

```
$ npm run docs

> @company/app@0.18.0 docs /mnt/s1/company/app
> run-s docs:apidoc docs:apidoc:md


> @company/app@0.18.0 docs:apidoc /mnt/s1/company/app
> apidoc -i source -o docs


> @company/app@0.18.0 docs:apidoc:md /mnt/s1/company/app
> apidoc-markdown -p docs -o API.md

(node:16237) UnhandledPromiseRejectionWarning: TypeError: ejs:28
    26| <%- sub.type.toUpperCase() %> <%= sub.url %>
    27| ```
 >> 28| <% if (sub.header && sub.header.fields && sub.header.fields.Header.length) { -%>
    29| 
    30| ### Headers
    31| | Name    | Type      | Description                          |

Cannot read property 'length' of undefined
    at eval (eval at compile (/mnt/s1/company/app/node_modules/apidoc-markdown/node_modules/ejs/lib/ejs.js:649:12), <anonymous>:71:72)
    at Array.forEach (<anonymous>)
    at eval (eval at compile (/mnt/s1/company/app/node_modules/apidoc-markdown/node_modules/ejs/lib/ejs.js:649:12), <anonymous>:55:19)
    at Array.forEach (<anonymous>)
    at eval (eval at compile (/mnt/s1/company/app/node_modules/apidoc-markdown/node_modules/ejs/lib/ejs.js:649:12), <anonymous>:47:13)
    at anonymous (/mnt/s1/company/app/node_modules/apidoc-markdown/node_modules/ejs/lib/ejs.js:679:17)
    at Object.exports.generate (/mnt/s1/company/app/node_modules/apidoc-markdown/dist/generator.js:69:37)
    at Object.exports.generateMarkdownFileSystem (/mnt/s1/company/app/node_modules/apidoc-markdown/dist/generator.js:127:35)
(node:16237) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16237) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Usage
Clone the repository at https://github.com/perry-mitchell/example-apidoc

Run `npm install` and `npm run docs` to reproduce the error.

### `api_project.json`
Used `api_project.json` file.

```json
{
    "name": "Test API",
    "version": "1.0.0",
    "description": "API for testing",
    "template": {
        "forceLanguage": "en"
    }
}
```

### `api_data.json`
Used `api_data.json` file.

_none_

**Expected behavior**
The documentation should build without error.

**Versions (please complete the following information):**
 - `Node.js` version: `12.16.1`
 - `TypeScript` version: _none_
 - `apiDoc` version: `0.22.1`
 - `apidoc-markdown` version: `5.0.2`

**Additional context**
Seems like this was addressed in #10 but subsequently closed without resolution. The issue for me seems like the **group** in the `@apiheader` line causes the issue. Removing it fixes the issue. This is contrary to the [documentation](https://apidocjs.com/#param-api-header).

In #10 it was also mentioned that the examples work, but note that the [current apidoc-markdown codebase doesn't seem to include an example for the group](https://github.com/rigwild/apidoc-markdown/search?q=apiHeader&unscoped_q=apiHeader).

I got the idea for adding the group from [this post](https://github.com/apidoc/apidoc/issues/139#issuecomment-323990930), as there was no clear way to document response headers.

**Comment by rigwild** [comment]
Thank you for all the informations. I knew there was some bug but could not find where with the limited feedback I got in previous issues. I will look into it soon.

Looks like [apidoc example](https://github.com/apidoc/apidoc/blob/master/example/example.js) (and [apidoc-example](https://github.com/apidoc/apidoc-example)) does not include it either.

**Comment by perry-mitchell** [comment]
@rigwild thanks for the quick response! Please let me know if I can help further with debugging. And thanks heaps for the library.

**Comment by rigwild** [comment]
Hi @perry-mitchell 😊 I fixed it.
Upgrade to `apidoc-markdown@5.1.0` and let me know if you still face issues with this.
