### ISSUE TITLE
Markdown tables should be preceded by a newline

### ISSUE THREAD

**Issue by dennislwm** [rigwild/apidoc-markdown#13]
## Describe the bug
I have a markdown page that uses table layout, and it shows correctly as table in a VS Code markdown preview plugin, but when I check it into GitHub, it doesn't display the tables correctly but rather displays the table markdown.

Markdown:

Inputs
| type|name |description |
|----|---|---|
| *address* | _user | address of certificate owner |
| *bytes32* | _hash | sha256 hash of the certificate text |

This shows on the page when viewed in GitHub:

Inputs | type | name | description | | ---- | --- | --- | | address | _user | address of certificate owner | | bytes32 | _hash | sha256 hash of the certificate text |

### Usage
Used `apidoc-markdown` command or script.

```bash
apidoc-markdown -p apidocs/ -o docs/index.md
```

**Expected behavior**

Inputs
| type         | name  | description                                     |
|------------|--------|--------------------------------------|
| *address* | _user  | address of certificate owner          |
| *bytes32* | _hash | sha256 hash of the certificate text |

**Versions (please complete the following information):**
 - `Node.js` version: `12.13.1` 
 - `apiDoc` version: `0.22.1`
 - `apidoc-markdown` version: `5.1.0`

**Additional context**
Problem was first reported here:
https://stackoverflow.com/questions/51579966/markdown-tables-not-displayed-on-a-github-md-page

**Comment by rigwild** [comment]
Hi. Thanks for the report.

GitHub's Markdown parser is usually very permissive with newlines in tables so its a pretty unexpected result.
Can you share a reproduction apidoc comment block ?

**Comment by dennislwm** [comment]
Hi. It appears to display correctly on GitHub, but not on GitHub pages.

Here is a sample document on both GitHub and Pages.

GitHub pages example:
http://dennislwm.github.io/expresso

GitHub example:
https://github.com/dennislwm/expresso/blob/master/docs/index.md

**Comment by rigwild** [comment]
Did not think about Github Pages. Can you confirm that manually adding a newline before the table fixes it ?

**Comment by dennislwm** [comment]
I've added a newline before the tables (1st to 3rd) in the example above.

Yes, it appears to fix the problem on GitHub Pages.

**Comment by rigwild** [comment]
Should be fixed in `v5.1.1`!
