### ISSUE TITLE
`--prepend` option doesn't work well

### ISSUE THREAD

**Issue by sorokinsh** [rigwild/apidoc-markdown#16]
## Describe the bug
`--prepend` option expect filename as value, but displays as file path not file content.

### Usage
Used `apidoc-markdown` command or script.

```bash
apidoc -i ./src/actions -i ./docs -o ./.apidoc && apidoc-markdown -p ./.apidoc -o ./README.md -t docs/apidoc-template/apidoc.ejs --prepend ./docs/before.md
```
**Expected behavior**
Content from `./docs/before.md` are displayed in documentation.

**Actual**
File path on 43:
![image](https://user-images.githubusercontent.com/825300/83522465-5e9e7680-a4e9-11ea-9e34-c1896ec1dbd0.png)

**Comment by rigwild** [comment]
Good catch, thanks!
