### ISSUE TITLE
Support the settings of `header` and `footer` in api_project.json

### ISSUE THREAD

**Issue by gslin** [rigwild/apidoc-markdown#19]
## Describe the bug
No `header` and `footer` support in `api_project.json`.

### Usage
Used `apidoc-markdown` command or script.

```bash
apidoc -i mycode/ doc/
apidoc-markdown -p doc/ -o index.md
```

### `apidoc.json`
The `apidoc.json` file is:

```json
{
    "name": "test",
    "version": "0.1.2",
    "description": "test",
    "title": "test",
    "url": "https://test.example.com/",
    "header": {
        "filename": "doc/header.md"
    },
    "footer": {
        "filename": "doc/footer.md"
    }
}
```

### `doc/header.md`
```
All inputs and outputs are `application/json` implicitly.
```

### `doc/header.md`
Empty file, 0 size.

**Expected behavior**
The wordings in `doc/header.md` should be put into `index.md` in this case.

**Versions (please complete the following information):**
 - `Node.js` version: `14.16.0`
 - `TypeScript` version: N/A
 - `apiDoc` version: `0.27.1`
 - `apidoc-markdown` version: `5.2.2`

**Comment by rigwild** [comment]
Good idea, I will add this. Thank you!

**Comment by rigwild** [comment]
Added in https://github.com/rigwild/apidoc-markdown/releases/tag/v5.2.3 😉
Thank you for the suggestion!
