### ISSUE TITLE
Confusing files

### ISSUE THREAD

**Issue by terrible-coder** [rigwild/apidoc-markdown#2]
How do you create the required `api_data.json` and `api_project.json`? There is no documentation regarding the creation of those files.
In case the ones in the `examples` directory can be simply copied into our own project source folder then it would be better to have them used along with the default template by default.
If the files are supposed to be specific to our project then the guidelines as to how to create (or generate) those files would be helpful.

**Comment by rigwild** [comment]
Hello @terrible-coder , 
Your issue is not related to the project. These files are generated using http://apidocjs.com/#run
It contains your API documentation data.
Have a nice day.
