### ISSUE TITLE
apidoc-markdown no longer working with apidoc 0.50.0

### ISSUE THREAD

**Issue by ManciuStefan** [rigwild/apidoc-markdown#20]
## Describe the bug
In the latest version of apidoc (0.50.0), the api_data.json and api_project.json files are no longer generated. This results in a crash for apidoc-markdown. I already discussed this with the apidoc maintainer [here](https://github.com/apidoc/apidoc/issues/1046) and he said he'll implement them again, but as a single file, so there will be some changes necessary on apidoc-markdown too. Just wanted to let you know. If you don't have the time, I'll give it a go once it's implemented in apidoc.

## Reproduce
Run apidoc
Run apidoc-markdown

**Expected behavior**
A generated markdown apidoc

**Versions (please complete the following information):**
 - `Node.js` version: `14`
 - `apiDoc` version: `0.50.0`
 - `apidoc-markdown` version: `6.0.1`

**Comment by rigwild** [comment]
Thank you for the report, I did not see this new release of apidoc. I updated the README to include a note to install v0.29.0 until it's fixed!

Keeping the issue open until resolved

**Comment by rigwild** [comment]
apidoc-markdown no longer needs apiDoc output files! :)

See https://github.com/rigwild/apidoc-markdown/releases/tag/v7.0.0
