### ISSUE TITLE
@apiBody and @apiQuery doesn't work

### ISSUE THREAD

**Issue by kryopix** [rigwild/apidoc-markdown#21]
## Describe the bug
`@apiBody` and `@apiQuery` don't work. I assumed that they would have to run like @apiParam, so I made a copy of the Parameters area in my own md template. But without success. 
When I took a closer look, I noticed that the key "fields" was completely missing in the data - subs - query/body object. 

### Usage
Use `apidoc-markdown` command.

```bash
apidoc-markdown -p ./example/basic -o ./example/basic/example.md -t ./myOwnTemplate.md
```

**Expected behavior**
I assumed that `@apiBody` and `@apiQuery` would have to run like `@apiParam`

**Versions (please complete the following information):**
 - `Node.js` version: `14.18.1`
 - `apidoc-markdown` version: `7.0.1`

**Additional context**
```
<% if (sub.parameter && sub.parameter.fields) { -%>
<% Object.entries(sub.parameter.fields).forEach(([parametersGroup, parametersGroupContent]) => { -%>

### Parameter - `<%= parametersGroup -%>`

| Name     | Typ        | Beschreibung                          |
|----------|------------|---------------------------------------|
<% parametersGroupContent.forEach(param => { -%>
| <%- param.field -%> | <%- param.type ? `\`${param.type}\`` : '' %> | <%- param.optional ? '**optional** ' : '' -%><%- param.description -%>
<% if (param.defaultValue) { -%>
_Default value: <%= param.defaultValue %>_<br><% } -%>
<% if (param.size) { -%>
_Size range: <%- param.size %>_<br><% } -%>
<% if (param.allowedValues) { -%>
_Allowed values: <%- param.allowedValues %>_<% } -%> |
<% }) // foreach parameters -%>
<% }) // foreach param parameter -%>
<% } // if parameters -%>

<%- Object.keys(sub.body[0]) %>
<%- Object.keys(sub.parameter.fields.Parameter[0]) %>
```

**Comment by rigwild** [comment]
Hey, you are right. I just checked and it was introduced last year in apiDoc! I was not aware of these :)

Added in https://github.com/rigwild/apidoc-markdown/releases/tag/v7.0.2
