### ISSUE TITLE
apidoc.json only in input dir works

### ISSUE THREAD

**Issue by Sozialarchiv** [rigwild/apidoc-markdown#22]
## Describe the bug

apidoc.json is only processed if it is placed in the input dir (e.g. src). 

If you place it in the project folder or in package.json it wont get processed.

`apidoc-markdown -i src -o apidoc`

**Comment by rigwild** [comment]
Should be fixed in https://github.com/rigwild/apidoc-markdown/releases/tag/v7.0.2 ! :) 
Thank you for the report!

**Comment by Sozialarchiv** [comment]
@rigwild Thank you very much for the fast fix and the great software.
