### ISSUE TITLE
Unable to generate docs marked with @apiPrivate as --private argument is not working

### ISSUE THREAD

**Issue by zionsg** [rigwild/apidoc-markdown#25]
## Describe the bug
Unable to generate docs marked with `@apiPrivate` as `--private` argument is not working

### Usage
Contents of `test/test.js`
```
/**
 * @api {get} /api/public-endpoint Public Endpoint
 * @apiName PublicEndpoint
 * @apiGroup ExampleApi
 */

/**
 * @apiPrivate
 * @api {post} /api/private-endpoint Private Endpoint
 * @apiName PrivateEndpoint
 * @apiGroup ExampleApi
 */
```

Used `apidoc-markdown` with `--private` argument to generate docs with both public and private endpoints 
but output `index.md` only shows public endpoint.

```bash
apidoc-markdown --input test/ --output test/index.md --private --verbose --debug
```

Parsed options showed that `private` flag was set to true.
```
[debug] Parsed options:
{
  _: [],
  input: 'test/',
  i: 'test/',
  output: 'test/index.md',
  o: 'test/index.md',
  private: true,
  p: true
}
```

But debug logs said that private flag was set to false.
```
debug: inspect file: test/test.js
debug: size: 240
debug: count blocks: 2
debug: count elements in block 0: 3
debug: count elements in block 1: 4
debug: api found in block: 0
debug: private flag is set to false and apiPrivate found in block: 1
debug: found @api in block: 0
debug: found @apiName in block: 0
debug: found @apiGroup in block: 0
```

### `package.json`
Used `apidoc` key in `package.json` file.

```json
{
  "apidoc": {
    "name": "API Documentation",
    "title": "Sample API",
    "url": "http://localhost"
  }
}
```

**Expected behavior**
Expected to see private endpoint marked with `@apiPrivate` to appear in generated docs.
Tested with `apidoc` and private endpoint was generated, i.e. `apidoc --input test/ --output test/ --single --private --verbose --debug`

**Versions (please complete the following information):**
 - `Node.js` version: `complete_this` [e.g. `16.15.0`]
 - `apiDoc` version: `complete_this` [e.g. `0.53.1`]
 - `apidoc-markdown` version: `complete_this` [e.g. `7.22.0`]

**Comment by rigwild** [comment]
Thanks for the report! I upgraded [Yargs](https://github.com/yargs/yargs) without double checking the release notes.
Fixed!

**Comment by zionsg** [comment]
Thanks for the fast response! Was looking thru the code changes in this repo but didn't think of looking at the dependencies :)
