### ISSUE TITLE
Not generating entry for each comment block when not providing `@api` title

### ISSUE THREAD

**Issue by ezmiller** [rigwild/apidoc-markdown#26]
## Describe the bug
apidoc-markdown is not creating entries for each comment block endpoint.

## Reproduce
I created a small repo [here](https://github.com/ezmiller/apimarkdown-issue) demonstrating the issue. I committed the `API.md` file but run `yarn doc` to regenerate.

### Usage
I created a small repo [here](https://github.com/ezmiller/apimarkdown-issue) demonstrating the issue. I committed the `API.md` file but run `yarn doc` to regenerate.

**Expected behavior**
I would have expected an entry for each comment-block definition. Instead I only got one.

**Versions (please complete the following information):**
 - `Node.js` version: `16.3.2`
 - `apiDoc` version: `0.53.1` 
 - `apidoc-markdowwwn` version: `7.2.4`

**Additional context**

**Comment by ezmiller** [comment]
What is odd about this is that when I turned on debug (`-d`), it looks like it knows there are three blocks:

```bash
debug: inspect file: src/test.js
debug: size: 294
debug: count blocks: 3
debug: count elements in block 0: 3
debug: count elements in block 1: 3
debug: count elements in block 2: 3
```

**Comment by rigwild** [comment]
Thanks the report ✌️

After investigating, the solution is to provide a title to the `@api` property, like this:

```js
/**
 * @api {get} /test Get a test
 * @apiName GetTest
 * @apiGroup Test
 */
function testGet() {}

/**
 * @api {post} /test Post a test
 * @apiName PostTest
 * @apiGroup Test
 */
function testPost() {}

/**
 * @api {post} /test/another Post another test
 * @apiName PostTestAnother
 * @apiGroup Test
 */
function testPostAnother() {}
```

As the `title` property is required (see https://apidocjs.com/#param-api), this is not a bug.

I will add a check and throw a error if one key is missing the `title` property.

**Comment by ezmiller** [comment]
Thank you for the speedy response @rigwild !
