### ISSUE TITLE
Missing required argument: apiDocPath

### ISSUE THREAD

**Issue by vanekj** [rigwild/apidoc-markdown#4]
Hello,

when I set parameter `--path`, the script throws an error:

```
Missing required argument: apiDocPath
```

When using the alias `-p`, it works well.

**Node version:** v12.7.0
**NPM version:** 6.13.0
**Package version:** 3.0.0

**Comment by rigwild** [comment]
Change it to `apiDocPath`. Will update doc. Thanks!
