### ISSUE TITLE
@apiError is not generated on markdown

### ISSUE THREAD

**Issue by rafaels-dev** [rigwild/apidoc-markdown#6]
`apidoc-markdown` isn't generating `@apiError` parameters.

I'm generating markdown file based on these comments:
```
/**
   * @api {get} /insured Get Insured
   * @apiGroup Insured
   * @apiName GetInsured
   * @apiParam (QueryString) {String} cpf   CPF do segurado
   * @apiParam (QueryString) {String} [email] E-mail do segurado. Não deve ser informado quando 'origin=backoffice' for informado.
   * @apiParam (QueryString) {String} [origin] Local de origem da chamada de API. Deve ser usado o valor 'backoffice' quando a chamada for feita pela interface de atendimento.
   * @apiExample {curl} Exemplo de requisição:
   *    curl -i http://localhost:7013/insured?cpf=000000000
   * @apiError 400 CPF não informado
   * @apiErrorExample {json} Erros 400 - Validação de campos
       { "errors": ["CPF não informado", "E-mail não informado"] }
   */
```
When I open _index.html_ file from `apiDoc` , I can see this table:
![image](https://user-images.githubusercontent.com/5066597/72279973-0c31eb80-3616-11ea-9e1f-f538b6132dc4.png)

But I can't find similar table or information when I open the markdown file, as you can see in [this gist](https://gist.github.com/rafaels-dev/a8090d246f896b442a20e17d4f0edba2)

**Comment by rigwild** [comment]
Hey @rafaels-dev,
I just check your gist and can see the error ?
![image](https://user-images.githubusercontent.com/26366184/72282897-ef111300-363d-11ea-9de1-43a3cf48453c.png)

Maybe I didn't understand the problem ?

**Comment by rafaels-dev** [comment]
Hi @rigwild this section you can see in your image is the `@apiErrorExample`, not `@apiError`. I can't see error "fields" from `api_docs.json`,
```
"error": {
      "fields": {
        "Error 4xx": [
          {
            "group": "Error 4xx",
            "optional": false,
            "field": "400",
            "description": "<p>CPF não informado</p>"
          }
        ]
      },
      "examples": [
        {
          "title": "Erros 400 - Validação de campos",
          "content": "{ \"errors\": [\"CPF não informado\", \"E-mail não informado\"] }",
          "type": "json"
        }
      ]
    },
```

**Comment by rafaels-dev** [comment]
"Error 4xx" and "Table with @apiError" is not generated in _markdown_ file.

**Comment by rigwild** [comment]
You are totally right! Responses are detailes in a table but not the errors.

I will fix it, thanks for your contribution 😄

**Comment by rigwild** [comment]
Fixed it and added more details for responses and errors.

Thanks for your issue! :)
