### ISSUE TITLE
@apiParamExample not rendering

### ISSUE THREAD

**Issue by michelpf** [rigwild/apidoc-markdown#9]
The parameter @apiParamExample is not rendering in markdown, but in HTML is.

Using first the apidoc regular command over the Python Flask file:

`apidoc -f ".*\\.py$"  -o docs/`

Then, generate the markdown files:

` apidoc-markdown -p docs/ -o  docs/readme.md`

**Comment by rigwild** [comment]
Hi @michelpf 

I did a major upgrade of the package. Mind trying with the new version ?

Also, providing your `apidoc_data.json` and `apidoc_project.json` files would help debug this issue.

**Comment by rigwild** [comment]
@michelpf Up.
